spring:
  datasource:
    url: jdbc:mysql://192.168.254.128/tale?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
    prefix: classpath/templates/
    suffix: .html
    servlet:
      content-type: text/html
#  redis:
#    database: 2
#    host: 192.168.2.128
#    port: 6379
#    timeout: 1000
#  data:
#    mongodb:
#      host: 192.168.2.128
#      port: 27017
#      database: oasystem
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exoa.oasystem.dao
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql